### ISSUE TITLE
Restarting X-UI after editing database

### ISSUE THREAD

**Issue by yousefjf** [NidukaAkalanka/x-ui-english#103]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I'm developing a telegram bot for x-ui.

When I add or renew an inbound, I have to send "x-ui restart" command in server terminal using ssh or clicking on "Revise" button in panel for my changes affect.

When I restart x-ui all of my inbounds gets offline for 5-10 seconds and its so annoying.

Is there a way that I can make x-ui update the database without restarting whole services?

### Version of x-ui

<details>

```console
$ x-ui version
# 0.2.1.2
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @yousefjf !

Wishing happy coding for developing the bot. 
When adding an inbound, upon clicking Add to, or Revise upon editing, the database automatically gets updated. No need of restarting it manually.

**Comment by yousefjf** [comment]
Isn't there any way to update database without clicking on Add or Revise?
When I create an account inside my telegram bot I can't revise all the time.
