### ISSUE TITLE
ip limitation not working

### ISSUE THREAD

**Issue by mostafa9112** [NidukaAkalanka/x-ui-english#104]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hi
ip limitation not working for me
What should I do?

### Version of x-ui

<details>

```console
$ x-ui version
# 0.2.1.2
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @mostafa9112 !

IP limitation is proven to be working in default fresh installation. If everything else is working fine, you might be misunderstanding how the IP limitation works. Please read [this ](https://github.com/NidukaAkalanka/x-ui-english/#ip-limitation-and-multi-user-on-same-port) thoroughly.
