### ISSUE TITLE
I am getting constantly this error WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email

### ISSUE THREAD

**Issue by amihos** [NidukaAkalanka/x-ui-english#106]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

X-ui is running normally but when i check logs I see this error constantly  happening and also the cpu usage is more than it should be

WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
x-ui-English 0.2.1.2


</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

repeating 
WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email

</details>

**Comment by aliafshany** [comment]
@amihos 
would you please try to contact with me in TG with this id: @Ali_afshany ?
i got the same issue here, maybe we can reach to a conclusion

**Comment by NidukaAkalanka** [comment]
Hi there @amihos and @aliafshany !

This isn't an issue actually. Just click the loop icon besides the Email and the issue would be resolved. (Refer the screenshot below)
![IMG_20230113_110607](https://user-images.githubusercontent.com/97357554/212245132-afac530a-6d41-4924-99ea-575bf8b54c9c.jpg)

You are getting this error because you are using same email twice.

**Comment by amihos** [comment]
@NidukaAkalanka I double checked in panel and found no single email that was duplicate. Still I was receiving this error message. So based on your explantion and then decided to explore the database and found out something weird. There were many inbounds from the past that I had deleted (or thought that I deleted them) and they were still in the database. So I think this is what is causing the issue. In other words, then you delete some email configs (sub clients of an inbound) they wont get delted in the database. 

I got rid of them manually in the database and now the problem got resolved. So I think the bug is in the panel not deleting actually from the database when you click on the panel.

**Comment by amihos** [comment]
Update: I just tested it and confirm this problem. Here is how to replicate: make a client with an email or name. Then delete it. and Make it again with the same name or email and the error starts to show up.

**Comment by aliafshany** [comment]
@amihos 
would you please give me an instruction to do that?
maybe a TG id would be helpful.
i got the same problem.

thanks.

**Comment by amihos** [comment]
> @amihos 
> would you please give me an instruction to do that?
> maybe a TG id would be helpful.
> i got the same problem.
> 
> thanks.

I contacted you on tg and explained
