### ISSUE TITLE
Migrate from hossinasaadi's x-ui

### ISSUE THREAD

**Issue by aliafshany** [NidukaAkalanka/x-ui-english#108]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hello there
I'd like to know if it is possible for you to implement a feature that we can migrate from hossinasaadi's x-ui to yours.
Unfortunately, the backup file won't be accepted in this repo's x-ui which was predictable.

best

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by subzero9319** [comment]
rename it

> ### Welcome
> * [x]  Yes, I'm using the latest major release. Only such installations are supported.
> * [x]  Yes, I'm using the supported system. Only such systems are supported.
> * [x]  Yes, I've searched similar issues on GitHub and didn't find any.
> * [x]  Yes, I've included all information below (version, config, log, etc).
> 
> ### Description of the problem,screencshot would be good
> hello there I'd like to know if it is possible for you to implement a feature that we can migrate from hossinasaadi's x-ui to yours. Unfortunately, the backup file won't be accepted in this repo's x-ui which was predictable.
> 
> best
> 
> ### Version of x-ui
> ### x-ui log or xray log

rename it from x-ui.db to x-ui-english.db
this can solve your problem

**Comment by aliafshany** [comment]
@subzero9319 
have you ever tested that by yourself?
my experience was unseccessful

**Comment by NidukaAkalanka** [comment]
Hi there @aliafshany!

Please refer here : https://github.com/NidukaAkalanka/x-ui-english/discussions/114

Should work if the code author has used the same base code

**Comment by subzero9319** [comment]
> 

yes bro
many time
