### ISSUE TITLE
No Backup panel user

### ISSUE THREAD

**Issue by NIKA5050** [NidukaAkalanka/x-ui-english#109]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

copy file db userpanel from etc folder x-ui english and paste on new vps not work !

### Version of x-ui

X-UI English 0.2.1.2

### x-ui log or xray log

X-UI English 0.2.1.2

**Comment by NidukaAkalanka** [comment]
Hi there @NIKA5050 !

Please refer [here](https://github.com/NidukaAkalanka/x-ui-english/discussions/114)
