### ISSUE TITLE
clients and calculating traffics

### ISSUE THREAD

**Issue by graymind123** [NidukaAkalanka/x-ui-english#112]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello sir
I have some questions about clients and calculating traffics, I appreciate, if you can help me:
1.  I am wondering why some of protocols don't support adding `clients`.
2.  If I realized correctly, at the moment there is no relationship between `client` table and `inbound` table.
3.  Is it safe use previous client(same ID, same email address) during adding new clients in other inbounds?
4.  What will happen if we use the same email address for different clients in different inbounds? does `clientTraffic `calculated for sum of all inbounds related to users with same Email address?

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
1) They don't support multi user on same port currently.
2) There's a relationship. 
3) Nope. Please use a fresh email / id. 
4) X ui crashes saying the email is previously used. A duplication
