### ISSUE TITLE
only xray version 1.6.4 available !!?

### ISSUE THREAD

**Issue by mastermehrdad** [NidukaAkalanka/x-ui-english#117]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi
The only version of xray present and available is version 1.6.4 and there is no other option !!?

### Version of x-ui

Jan 17 18:53:07 pserver.space x-ui[410]: 2023/01/17 18:53:07 x-ui-english 0.2.1.2

### x-ui log or xray log

Jan 17 20:53:12 pserver.space systemd[1]: Stopping x-ui Service...
Jan 17 20:53:12 pserver.space systemd[1]: x-ui.service: Succeeded.
Jan 17 20:53:12 pserver.space systemd[1]: Stopped x-ui Service.
Jan 17 20:53:22 pserver.space systemd[1]: Started x-ui Service.
Jan 17 20:53:22 pserver.space systemd[1]: Stopping x-ui Service...
Jan 17 20:53:22 pserver.space systemd[1]: x-ui.service: Succeeded.
Jan 17 20:53:22 pserver.space systemd[1]: Stopped x-ui Service.
Jan 17 20:53:22 pserver.space systemd[1]: Started x-ui Service.
Jan 17 20:53:23 pserver.space x-ui[30485]: 2023/01/17 20:53:23 x-ui-english 0.2.1.2
Jan 17 20:53:23 pserver.space x-ui[30485]: 2023/01/17 20:53:23 INFO - web server run https on [::]:54321
Jan 17 20:53:23 pserver.space x-ui[30485]: 2023/01/17 20:53:23 INFO - Tg notify enabled,run at @every 30m
Jan 17 20:54:23 pserver.space systemd[1]: Stopping x-ui Service...
Jan 17 20:54:23 pserver.space systemd[1]: x-ui.service: Succeeded.
Jan 17 20:54:23 pserver.space systemd[1]: Stopped x-ui Service.
Jan 17 20:54:28 pserver.space systemd[1]: Started x-ui Service.
Jan 17 20:54:29 pserver.space x-ui[30843]: 2023/01/17 20:54:29 x-ui-english 0.2.1.2
Jan 17 20:54:29 pserver.space x-ui[30843]: 2023/01/17 20:54:29 INFO - web server run https on [::]:54321
Jan 17 20:54:29 pserver.space x-ui[30843]: 2023/01/17 20:54:29 INFO - Tg notify enabled,run at @every 30m

**Comment by NidukaAkalanka** [comment]
Hi there @mastermehrdad !

Please read the [pinned issue.](https://github.com/NidukaAkalanka/x-ui-english/issues/81) 
I'm planning to update the version ASAP
