### ISSUE TITLE
database connection

### ISSUE THREAD

**Issue by iaminnasr** [NidukaAkalanka/x-ui-english#118]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hi
I want to know how I can connect to the database from outside ؟

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by efakhimi** [comment]
Hi,
in this version database location is /etc/x-ui-english/x-ui-english.db
and in original x-ui the default location is /etc/x-ui/x-ui.db

The database type is sqlite and you can use the sqlite libs to connect and manipulate the data but please be careful.


python sample for read inbounds for this version
```
import sqlite3;

db_address = '/etc/x-ui-english/x-ui-english.db'
conn = sqlite3.connect(_db_address)

#get all inbounds
inbounds = conn.execute(f"select * from inbounds where true");
```
