### ISSUE TITLE
Traffic reset key

### ISSUE THREAD

**Issue by shahrooz1349** [NidukaAkalanka/x-ui-english#120]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi dear developer @NidukaAkalanka 
There is no key to reset individual user traffic Please add if key
With respect

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @shahrooz1349 and @subzero9319 !

Sure. Will give it a try. Stay excited to experience your requested feature on an upcoming release. 

Till then, you may consider deleting the client you want to reset the traffic and remaking it with the same uuid. Sorry for the inconvenience btw

**Comment by shahrooz1349** [comment]
> Hi there @shahrooz1349 and @subzero9319 !
> 
> Sure. Will give it a try. Stay excited to experience your requested feature on an upcoming release.
> 
> Till then, you may consider deleting the client you want to reset the traffic and remaking it with the same uuid. Sorry for the inconvenience btw

thank you
