### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by esi-th** [NidukaAkalanka/x-ui-english#122]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Dear Developer

When I access the panel, I get the following error:

ERR_SSL_PROTOCOL_ERROR

Sometimes it is fixed by itself

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @esi-th !

If you haven't configured SSL for your panel yet, please use `http://server-ip:port` for web access.

If you have configured SSL, then use `https://subdomain:port`
