### ISSUE TITLE
Not supporting trojan multi_user on same port

### ISSUE THREAD

**Issue by hossein-mohseni** [NidukaAkalanka/x-ui-english#125]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Can you please add trojan with multi_user

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @hossein-mohseni !

Sure. Will give it a try. Stay excited to experience your requested feature in an upcoming release.
