### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Angize** [NidukaAkalanka/x-ui-english#126]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

x-ui.service - x-ui Service
     Loaded: loaded (/etc/systemd/system/x-ui.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-01-24 15:31:41 +0330; 2h 19min ago
    Process: 1083929 ExecStart=/usr/local/x-ui/x-ui (code=exited, status=2)
   Main PID: 1083929 (code=exited, status=2)

Jan 24 15:31:40 ubuntu20 x-ui[1083929]: x-ui/web/job.processLogFile()
Jan 24 15:31:40 ubuntu20 x-ui[1083929]:         /home/runner/work/x-ui-english.dev/x-ui-english.dev/web/job/check_clinet_ip_job.go:100>Jan 24 15:31:40 ubuntu20 x-ui[1083929]: x-ui/web/job.(*CheckClientIpJob).Run(0x0?)
Jan 24 15:31:40 ubuntu20 x-ui[1083929]:         /home/runner/work/x-ui-english.dev/x-ui-english.dev/web/job/check_clinet_ip_job.go:34 >Jan 24 15:31:40 ubuntu20 x-ui[1083929]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Jan 24 15:31:40 ubuntu20 x-ui[1083929]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
Jan 24 15:31:40 ubuntu20 x-ui[1083929]: created by github.com/robfig/cron/v3.(*Cron).startJob
Jan 24 15:31:40 ubuntu20 x-ui[1083929]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad
Jan 24 15:31:40 ubuntu20 systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 24 15:31:41 ubuntu20 systemd[1]: x-ui.service: Failed with result 'exit-code'.

I get this error every few hours and it crashes the whole x-ui automatically

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Angize** [comment]
Hello???

**Comment by Angize** [comment]
Are you ok?
are you alive?

**Comment by Angize** [comment]
I'm worried about you, friend🥲🥲🥲

**Comment by Angize** [comment]
Do you not come to Telegram, friend?
i have work with you

**Comment by NidukaAkalanka** [comment]
> I get this error every few hours and it crashes the whole x-ui automatically
>
Seems like you have provided invalid arguments when creating clients or in panel settings. Maybe in telegram bot notification time or ip limit. Please check them out. If the issue exists contineously or if you think you have given everything correctly, please feel free to comment down with any other information if any.

**Comment by Angize** [comment]
> > I get this error every few hours and it crashes the whole x-ui automatically
> 
> Seems like you have provided invalid arguments when creating clients or in panel settings. Maybe in telegram bot notification time or ip limit. Please check them out. If the issue exists contineously or if you think you have given everything correctly, please feel free to comment down with any other information if any.

I use iplimit and I encounter this
Please tell me the solution

**Comment by Angize** [comment]
Everything enters correctly
And I use IP limit
What should I do to solve my problem?

**Comment by NidukaAkalanka** [comment]
To limit IP, just enter the number of IPs you want to be connected simultaneously. Like.. 1, 2.. Just a number. To disable it, enter 0

**Comment by Angize** [comment]
I enter everything correctly but still after a few hours I get the error again
