### ISSUE TITLE
sources is not up-to-date

### ISSUE THREAD

**Issue by gitd3v** [NidukaAkalanka/x-ui-english#129]
Hi, 
first thanks for your great work
it seems the source codes of 0.2.1.2 is not provided
building project from source code does not generate same functionality as binary provided

it's appreciated  to provide codes on github
(main branch, tag 0.2.1.2 and tar.gz from release page is tried)

**Comment by NidukaAkalanka** [comment]
Hi there @gitd3v !

For every release, a link to the git repo for each source code is provided at the end of the release notes. Please refer the screenshot below. 

Will try to merge these two repos ASAP.
![Screenshot_2023-01-27-09-20-01-825-edit_com android chrome](https://user-images.githubusercontent.com/97357554/215006035-29546489-9904-4f19-b1e8-28d3c91b28e2.jpg)
