### ISSUE TITLE
request add connection limiter to Project

### ISSUE THREAD

**Issue by moslem2013** [NidukaAkalanka/x-ui-english#13]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hi @NidukaAkalanka 
please Add connection limiter to the Project 
https://github.com/net-pioneer/v2ray-connection-limiter
with this script you can detect and ban those V2ray accounts which aren't only connected to one devices.
can set  max_allowed_connections

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi @moslem2013 , 
Sure! This is already a successfully implemented function in the next release. See the screenshot below. Stay excited to experience your requested feature on version 0.2.1.; which will be released soon!

![Screenshot (23)](https://user-images.githubusercontent.com/97357554/201837274-9d0729a8-8082-4255-91a0-10c745eb4e13.png)

**Comment by moslem2013** [comment]
thanks

**Comment by NidukaAkalanka** [comment]
Hey @moslem2013 !
Please check the [Release 0.2.1](https://github.com/NidukaAkalanka/x-ui-english/releases/tag/0.2.1). It has this particular issue was resolved.
Thanks a lot for your contribution via opening up this issue, also!
Regards,
🤍

**Comment by hadiceberg** [comment]
I guess this won't work when the server is behind CDN proxy, right? Cause all that the server sees is CDN IPs.
Do you Think this can be implemented using X-Forwarded-For HTTP header? The challenge is that I think the pyton script won't be able to manage this. This is something that should be done in xray-core!
