### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by moslem2013** [NidukaAkalanka/x-ui-english#14]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi @NidukaAkalanka  After creating the account, when we Enable TLS, if we forget to enter the certificate and private key and create the account, all Created accounts will be disconnected And Not Connect

![1](https://user-images.githubusercontent.com/53048658/202081103-65701efa-6f89-4168-bd03-d6015f549bc3.jpg)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi again, @moslem2013 ,
Yeap. It's not a bug though.. It's the default behavior of X UI. If you turn on TLS, you got to provide valid absolute paths to certificate.crt and private.key. Panel doesn't know where're those files. 
When issuing SSL via the inbuilt acme.sh, it'll show you where those files are. Remember the paths and apply them whenever needed.
