### ISSUE TITLE
Per user traffic report

### ISSUE THREAD

**Issue by ysmoradi** [NidukaAkalanka/x-ui-english#15]
Thanks for the "Multi-user" feature which is fantastic!
It would be a great idea to add a traffic report for each user in addition to having it per inbound
Many thanks for considering my request.

**Comment by NidukaAkalanka** [comment]
Hi @ysmoradi ,
It's a pleasure to hear a compliment so thank you back for that! I'm currently working on generating different QR codes for each multi user UUIDs separately; which will be even more "fantastic" 
You are asking for traffic monitoring per UUID, right? Yeah. You may be experiencing such a feature in upcoming releases. So, stay excited!

**Comment by ysmoradi** [comment]
Awesome! 🌷💫🌱💯🎉 (":

**Comment by hossinasaadi** [comment]
> Thanks for the "Multi-user" feature which is fantastic! It would be a great idea to add a traffic report for each user in addition to having it per inbound Many thanks for considering my request.
hi @ysmoradi check it out  
https://github.com/hossinasaadi/x-ui

**Comment by ysmoradi** [comment]
Thanks for your offer @hossinasaadi 
I compared your and @NidukaAkalanka code base and even though they're coming from the same codebase, both have many differences. In the meaning time, I'd like to continue using @NidukaAkalanka because I've spent a lot of time testing that and I don't have much time to start the testing process from scratch.
I'll give it a try later

**Comment by NidukaAkalanka** [comment]
Hey @ysmoradi !
Please check the [Release 0.2.1](https://github.com/NidukaAkalanka/x-ui-english/releases/tag/0.2.1). It has this particular issue was resolved.
Thanks a lot for your contribution via opening up this issue, also!
Regards,
🤍

**Comment by NidukaAkalanka** [comment]
Hey @ysmoradi !
Please check the [Release 0.2.1](https://github.com/NidukaAkalanka/x-ui-english/releases/tag/0.2.1). It has this particular issue was resolved.
Thanks a lot for your contribution via opening up this issue, also!
Regards,
🤍
