### ISSUE TITLE
IP limit does not deactivates the client account

### ISSUE THREAD

**Issue by odeaxcsh** [NidukaAkalanka/x-ui-english#155]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

It would be nice if there was an option to specify the kind of behavior we expect the restriction do when a limit reaches. 

Specifically IP limit, for example, when there is a limit of 2 devices, I expect that the third device causes the account to be deactivated. 

This doesn't need the IP logs be saved, and only the number of current active connections are needed as client restriction.

### Version of x-ui

<details>

Latest Version 0.2.1.2

</details>

### x-ui log or xray log

<details>

``` console 
# Paste log here
```
</details>

**Comment by dar1366** [comment]
hi , i have the same problem 
When the number of IPs exceeds the specified number, the account will not be deactivated

**Comment by behzadti** [comment]
> hi , i have the same problem When the number of IPs exceeds the specified number, the account will not be deactivated

me too

**Comment by NidukaAkalanka** [comment]
Please refer here and understand how is this feature's normal behavior. https://github.com/NidukaAkalanka/x-ui-english#ip-limitation-and-multi-user-on-same-port
