### ISSUE TITLE
x-ui crashes

### ISSUE THREAD

**Issue by KennyMcKormik** [NidukaAkalanka/x-ui-english#159]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi 

x-UI crashes and exits due to a memory error.

### Version of x-ui

<details>

 x-ui-english 0.2.1.2

</details>

### x-ui log or xray log

<details>

Feb 28 11:30:26 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               30:26 WARNING - add traffic failed: database is locked; no valid transaction; no                                                                                                                                valid transaction
Feb 28 11:30:44 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               30:44 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_t                                                                                                                               raffics.email
Feb 28 11:30:49 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               30:49 WARNING - disable invalid Client err: database is locked
Feb 28 11:30:49 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               30:49 WARNING - add traffic failed: database is locked; no valid transaction
Feb 28 11:30:49 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               30:49 WARNING - add traffic failed: database is locked; no valid transaction
Feb 28 11:30:49 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               30:49 WARNING - add traffic failed: database is locked; no valid transaction
Feb 28 11:30:49 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               30:49 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_t                                                                                                                               raffics.email
Feb 28 11:30:54 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               30:54 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:30:54 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               30:54 WARNING - disable invalid inbounds err: database is locked
Feb 28 11:30:55 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               30:55 WARNING - disable invalid Client err: database is locked
Feb 28 11:30:55 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               30:55 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_t                                                                                                                               raffics.email
Feb 28 11:30:59 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               30:59 WARNING - add traffic failed: database is locked; no valid transaction; no                                                                                                                                valid transaction
Feb 28 11:31:00 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:00 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:00 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:00 WARNING - disable invalid inbounds err: database is locked
Feb 28 11:31:00 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:00 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:04 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:04 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:09 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:09 WARNING - add traffic failed: database is locked; no valid transaction
Feb 28 11:31:10 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:10 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:10 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:10 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:14 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:14 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:19 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:19 WARNING - add traffic failed: database is locked; no valid transaction; no                                                                                                                                valid transaction
Feb 28 11:31:20 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:20 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:20 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:20 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:20 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:20 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:24 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:24 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:25 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:25 WARNING - disable invalid Client err: database is locked
Feb 28 11:31:30 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:30 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:30 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:30 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:30 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:30 WARNING - disable invalid inbounds err: database is locked
Feb 28 11:31:30 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:30 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_t                                                                                                                               raffics.email
Feb 28 11:31:30 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:30 WARNING - add traffic failed: database is locked; no valid transaction
Feb 28 11:31:34 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:34 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:39 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:39 WARNING - add traffic failed: database is locked; no valid transaction; no                                                                                                                                valid transaction
Feb 28 11:31:40 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:40 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:40 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:40 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:40 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:40 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:44 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:44 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:49 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:49 WARNING - add traffic failed: database is locked; no valid transaction; no                                                                                                                                valid transaction
Feb 28 11:31:50 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:50 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:50 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:50 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:50 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:50 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:55 WARNING - disable invalid Client err: database is locked
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:55 WARNING - AddClientTraffic update data  database is locked
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]: 2023/02/28 11:                                                                                                                               31:55 WARNING - client ip job err: database is locked
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]: panic: runtime                                                                                                                                error: invalid memory address or nil pointer dereference
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]: [signal SIGSEG                                                                                                                               V: segmentation violation code=0x1 addr=0x90 pc=0xae86ab]
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]: goroutine 1078                                                                                                                               18 [running]:
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]: x-ui/web/job.u                                                                                                                               pdateInboundClientIps(0xc000384090, {0xc000688103, 0x14}, {0xc0006e0500?, 0x1, 0                                                                                                                               x1})
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]:         /home/                                                                                                                               runner/work/x-ui-english.dev/x-ui-english.dev/web/job/check_clinet_ip_job.go:195                                                                                                                                +0x24b
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]: x-ui/web/job.p                                                                                                                               rocessLogFile()
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]:         /home/                                                                                                                               runner/work/x-ui-english.dev/x-ui-english.dev/web/job/check_clinet_ip_job.go:100                                                                                                                                +0x40a
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]: x-ui/web/job.(                                                                                                                               *CheckClientIpJob).Run(0x0?)
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]:         /home/                                                                                                                               runner/work/x-ui-english.dev/x-ui-english.dev/web/job/check_clinet_ip_job.go:34                                                                                                                                +0x65
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]: github.com/rob                                                                                                                               fig/cron/v3.(*Cron).startJob.func1()
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]:         /home/                                                                                                                               runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]: created by git                                                                                                                               hub.com/robfig/cron/v3.(*Cron).startJob
Feb 28 11:31:55 vm1049922.stark-industries.solutions x-ui[19837]:         /home/                                                                                                                               runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad
Feb 28 11:31:55 vm1049922.stark-industries.solutions systemd[1]: x-ui.service: M                                                                                                                               ain process exited, code=exited, status=2/INVALIDARGUMENT
Feb 28 11:31:55 vm1049922.stark-industries.solutions systemd[1]: x-ui.service: F                                                                                                                               ailed with result 'exit-code'.

</details>

**Comment by wikilinux-ir** [comment]
hello.
i have same problem

**Comment by NidukaAkalanka** [comment]
It's not a memory error. You have used an email for a user which was previously used. Change the emails for users to a never used one and you'll be fine
