### ISSUE TITLE
Routing rules issue

### ISSUE THREAD

**Issue by ysmoradi** [NidukaAkalanka/x-ui-english#16]
You can change xray settings at `xui/setting` page
By default it has the followings:
![image](https://user-images.githubusercontent.com/5352980/202138031-69ed4e56-3e0b-4a20-934b-1c370f8d0b89.png)
But after I connect to the server using v2rayn.exe, `BitTorrent` clients continue working )":
I've enabled sniffing on inbounds
How can I prevent users from accessing `bittorrent`?
Thank you so much for your attention and participation.

Additional context:
I'm testing with `qBittorrent` client

**Comment by ysmoradi** [comment]
It seems that torrent clients are using advanced encryption mechanisms in order to prevent getting blocked
When I disable encryption in qTorrent settings, it gets blocked

**Comment by NidukaAkalanka** [comment]
Hi, again, @ysmoradi !
Honestly, I didn't test this out as I'm not much into Torrents.
However, I just found out a shell script that says it can block the v2ray clients from downloading torrents at [here](https://github.com/Heclalava/blockpublictorrent-iptables). ([Refernce](https://github.com/v2fly/v2ray-core/issues/1042#issuecomment-854271341))
As you said you were testing, I propose you try this out. If you gonna have positive results, consider being a contributor to the project by yourself. If not, I'll mention you at the readme after releasing a newer version with this function implemented.
By the way, use this at your own risk. If you do so, appreciate it a lot.
Thanks

**Comment by ysmoradi** [comment]
As far as I know, there's nothing we can do with encrypted torrent communications in order to completely block the clients from using it
There are some workarounds though, but I'm good with v2ray default config that blocks unencrypted torrent requests
