### ISSUE TITLE
Unable to connect to the server on Android

### ISSUE THREAD

**Issue by ysmoradi** [NidukaAkalanka/x-ui-english#17]
When I connect to the server using v2rayn.exe on Windows, it gets connected, but using the same network, I and my colleagues are unable to connect on Android phones using v2rayng mobile app (even with the latest pre release)

Note that we've some other servers configured with the Chinese script and we're able to connect to them on mobile devices too

**Comment by ysmoradi** [comment]
Setting "allow Insecure" fixes the issue but this is an ugly workaround
Why this happens only on mobile device?

**Comment by NidukaAkalanka** [comment]
Is it the first time you allowed insecure? Like.. I myself and the people that I share my v2ray configs always allow insecure. 
Does your pc client having insecure allowed by default?

**Comment by ysmoradi** [comment]
In PC, the "allow insecure" value is false and it works perfectly even with the new server
Yes, this is the first time (and for android only) and I think this is not a good idea to set it to false

**Comment by ysmoradi** [comment]
Additional context: All servers that I've are behind Cloudflare, and I'm putting this one behind Cloudflare too to see what happens next and will let you know about the outcome

**Comment by ysmoradi** [comment]
Yes, behind Cloudflare, android phone gets connected without such a workaround
