### ISSUE TITLE
Get release 0.1

### ISSUE THREAD

**Issue by hamedap** [NidukaAkalanka/x-ui-english#18]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi .
I search for release 0.1 and not found it .
Would you please add to release .
That release had less bug and problem .

Kind Regards

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @hamedap ,
The release version that you are looking for lives here: https://github.com/NidukaAkalanka/x-ui-english.old
Even I agree it had fewer bugs. But also fewer features. Will keep trying to make a release with more features and fewer bugs.
Thanks and Regards!
