### ISSUE TITLE
Telegram doesn't respond!

### ISSUE THREAD

**Issue by MNBoy** [NidukaAkalanka/x-ui-english#182]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I use latest version of x ui but telegram doesn't respond
<img width="1236" alt="Screenshot 2023-04-16 at 2 48 47 PM" src="https://user-images.githubusercontent.com/57574386/232305938-0bdfd23a-2eb8-4c58-be94-da6d87d3df58.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/57574386/232305946-96b6c45e-609d-4590-ba41-2e468c93895f.png">

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
Apr 16 12:21:55 unistart.ir x-ui[8036]: 2023/04/16 12:21:55 WARNING - stop server err: multierr: close tcp [::]:2701: use of closed network connection |
Apr 16 12:21:55 xxxx.ir x-ui[8036]: 2023/04/16 12:21:55 INFO - web server run http on [::]:2701
Apr 16 12:21:55 xxxx.ir x-ui[8036]: 2023/04/16 12:21:55 INFO - Tg notify enabled,run at @daily
```

</details>

**Comment by NidukaAkalanka** [comment]
Refer here : https://github.com/NidukaAkalanka/x-ui-english/issues/132
