### ISSUE TITLE
how to update to x-ui 1.80 

### ISSUE THREAD

**Issue by U-nanimou-S** [NidukaAkalanka/x-ui-english#186]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

how to update to x-ui 1.80  with out loseing our data list menu 

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by ir00ni** [comment]
نه آپدیت میشه نه میشه تبدیل کرد به پنل دیگه

**Comment by AlimahboubiNejad** [comment]
کسشعره محضه

**Comment by AlimahboubiNejad** [comment]
دولوپر حزومزاده سریلانکاییش مرده فکر کنم

**Comment by NidukaAkalanka** [comment]
https://github.com/NidukaAkalanka/x-ui-english/discussions/114
