### ISSUE TITLE
Create more than 10 user is not possible for each inbound

### ISSUE THREAD

**Issue by mahdavimahan** [NidukaAkalanka/x-ui-english#187]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi 
Create more than 10 user is not possible for each inbound listener.

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
It's not a issue. It's a limitation, which is default
