### ISSUE TITLE
change default domain

### ISSUE THREAD

**Issue by Aronablade** [NidukaAkalanka/x-ui-english#189]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hi , i wanted to know how can i change the default domain for inbounds , as you know when you make a new inbound (no tls) the panel take the panel domain and put it on the inbounds , but how can i change it and put a custom domain on inbounds , for example
my panel is on t1.domain.com:8880 i open the panel with this link and create an inbound , panel put the t1.domain.com as address on my configs , but i wanna load the panel with t1.domain.com but on my inbounds t2.domain.com be as the address on configs , how can i change it ?

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Edit the domain after adding the configuration to your client software. If you wanna share it with the edited host, export the uri from there
