### ISSUE TITLE
نه آپدیت میشه نه میشه تبدیل کرد به پنل دیگه

### ISSUE THREAD

**Issue by ir00ni** [NidukaAkalanka/x-ui-english#190]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

نه آپدیت میشه
 نه میشه دیتابیس تبدیل کرد به پنل دیگه

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Open up a issue describing your problem in English.
