### ISSUE TITLE
panel error

### ISSUE THREAD

**Issue by FarnamJavadi** [NidukaAkalanka/x-ui-english#192]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

it shows me this error

Xray 1.6.4 (Xray, Penetrates Everything.) 2942f56 (go1.19.3 linux/amd64)

A unified platform for anti-censorship.

2023/07/28 07:30:21 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: Failed to build XTLS config. > infra/conf: failed to parse certificate > open /root/cert.crt: no such file or directory

![Screenshot 2023-07-28 105951](https://github.com/NidukaAkalanka/x-ui-english/assets/67758766/24b87d95-89ff-4cb0-aff3-a415d891e8c8)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
You should first issue an ssl certificate and a key from the cli and then type it's path in the xtls / tls config's certificate path and key path fields. Not a global error.

**Comment by ali73** [comment]
> You should first issue an ssl certificate and a key from the cli and then type it's path in the xtls / tls config's certificate path and key path fields. Not a global error.

Where should we apply these configurations in Ubuntu OS?
