### ISSUE TITLE
traffic 

### ISSUE THREAD

**Issue by Angize** [NidukaAkalanka/x-ui-english#25]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Consumption traffic is not calculated
It has a problem

Transmission: tcp
http camouflage: active

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi @Angize !
Was it a fresh installation or an upgrading ? If it was an upgrade you got to modify the xray config template accordingly

**Comment by Angize** [comment]
you have telegram?

**Comment by NidukaAkalanka** [comment]
> you have telegram?

Yeap. https://t.me/NidukaAkalanka
It's mentioned on my readme also
