### ISSUE TITLE
IP Limitation Doesn't Work

### ISSUE THREAD

**Issue by SKRapToR20** [NidukaAkalanka/x-ui-english#26]
ip limitation doesn't work in version 0.2.1, anybody can connect with only one user, and it doesn't show connected ips in ip record section. shows NO IP Records . please fix .

**Comment by NidukaAkalanka** [comment]
Hi @SKRapToR20 !
Please refer to this link to understand how IP limitation works : https://github.com/NidukaAkalanka/x-ui-english/tree/0.2.1.1#ip-limitation-and-multi-user-on-same-port
Still, if you think there's something wrong with your panel, inform me with your Xray config template and x-ui log.
Thanks!

**Comment by NidukaAkalanka** [comment]
Thanks for it. You did an upgrade right? Please  apply the workaround here : https://github.com/NidukaAkalanka/x-ui-english/discussions/27
Will try to make it automated upon upgrading on an upcoming release. 
Please let me know if your issue got resolved after the simple workaround mentioned in the given link.

**Comment by NidukaAkalanka** [comment]
And make sure the xray version is 1.6.4 or 1.6.5 running
