### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by fsh230** [NidukaAkalanka/x-ui-english#31]
Hello
I encounter this error many times.
both in creating users and also making changes in existing users.

"Obtainfail: database is locked"
"Add to fail: database is locked"

" WARNING - add traffic failed: database is locked; no valid transaction "
This error is seen many times in the log x-ui.

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
" WARNING - add traffic failed: database is locked; no valid transaction "
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @fsh230 !
Weird issue though. Was it an upgrade or fresh installation? Did you manually take a backup of /etc/xui/x-ui.db if it was an upgrade?

**Comment by fsh230** [comment]
> Hi there @fsh230 ! Weird issue though. Was it an upgrade or fresh installation? Did you manually take a backup of /etc/xui/x-ui.db if it was an upgrade?

hi tihis is fresh installation.

**Comment by fsh230** [comment]
this is log x-ui :
Nov 28 18:14:42 VM********** x-ui[4943]: 2022/11/28 18:14:42 WARNING - add traffic failed: database is locked; no valid transaction; no valid transaction
Nov 28 18:15:12 VM********** x-ui[4943]: 2022/11/28 18:15:12 WARNING - add traffic failed: database is locked; no valid transaction
Nov 28 18:15:27 VM********** x-ui[4943]: 2022/11/28 18:15:27 ERROR - restart xray failed: database is locked
Nov 28 18:15:27 VM********** x-ui[4943]: 2022/11/28 18:15:27 WARNING - disable invalid Client err: database is locked
Nov 28 18:15:42 VM********** x-ui[4943]: 2022/11/28 18:15:42 WARNING - add traffic failed: database is locked; no valid transaction
Nov 28 18:16:17 VM********** x-ui[4943]: 2022/11/28 18:16:17 ERROR - restart xray failed: database is locked
Nov 28 18:16:22 VM********** x-ui[4943]: 2022/11/28 18:16:22 WARNING - add traffic failed: database is locked; no valid transaction; no valid transaction
Nov 28 18:20:12 VM********** x-ui[4943]: 2022/11/28 18:20:12 WARNING - add traffic failed: database is locked; no valid transaction
Nov 28 18:31:47 VM********** x-ui[4943]: 2022/11/28 18:31:47 ERROR - restart xray failed: database is locked
Nov 28 18:35:57 VM********** x-ui[4943]: 2022/11/28 18:35:57 WARNING - disable invalid Client err: database is locked
Nov 28 18:36:02 VM********** x-ui[4943]: 2022/11/28 18:36:02 WARNING - add traffic failed: database is locked; no valid transaction; no valid transaction
Nov 28 18:36:02 VM********** x-ui[4943]: 2022/11/28 18:36:02 WARNING - disable invalid inbounds err: database is locked
Nov 28 18:36:12 VM********** x-ui[4943]: 2022/11/28 18:36:12 WARNING - add traffic failed: database is locked; no valid transaction
Nov 28 18:36:22 VM********** x-ui[4943]: 2022/11/28 18:36:22 WARNING - add traffic failed: database is locked; no valid transaction
Nov 28 18:36:28 VM********** x-ui[4943]: 2022/11/28 18:36:27 WARNING - disable invalid Client err: database is locked
Nov 28 18:36:32 VM********** x-ui[4943]: 2022/11/28 18:36:32 WARNING - add traffic failed: database is locked; no valid transaction
Nov 28 18:36:32 VM********** x-ui[4943]: 2022/11/28 18:36:32 WARNING - disable invalid inbounds err: database is locked
Nov 28 19:13:12 VM********** x-ui[4943]: 2022/11/28 19:13:12 WARNING - add traffic failed: database is locked; no valid transaction

Please view and comment
Where is the problem and what should I do?
When it gives this error, the service is stopped and I have to start the service manually

**Comment by NidukaAkalanka** [comment]
Please consider reinstalling the x ui. I hadn't encountered  an users with such an issue
