### ISSUE TITLE
Telegram bot doesn't work!

### ISSUE THREAD

**Issue by MNBoy** [NidukaAkalanka/x-ui-english#32]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

<img width="611" alt="Screen Shot 2022-11-27 at 6 23 56 PM" src="https://user-images.githubusercontent.com/57574386/204141750-6ce1f2aa-4d68-4e20-b091-e297858f551f.png">

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi @MNBoy !
Yeah.. The latest version is installed when using the one click installation command and it's v0.2.1.1. On the readme, it is clearly stated that telegram bot is only available for v0.2. If you desperately want to experience telegram bot, please use 0.2 version tag at the end of installation command. Or, you can just wait a few days until I implement the telegram bot into the latest release. Stay excited then
