### ISSUE TITLE
Telegram bot not working

### ISSUE THREAD

**Issue by mehtiamgh** [NidukaAkalanka/x-ui-english#36]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hi
telegram bot and change vesrion of x-ui to 1.6.5 not working for me
how can i fix this problem?

### Version of x-ui

<details>

```console
$ x-ui version
# 1.6.4
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi @mehtiamgh !
As stated [here](https://github.com/NidukaAkalanka/x-ui-english#telegram-bot-preview-currently-only-for-v02) , the telegram bot is currently available only for the version 0.2
Changing the xray version isn't something recommended. If you change it to another version which isn't the default, you may end up getting a xray status error. If no errors are encountered, you may lose features such as ip limitation, per client traffic monitoring, multi user on same port and etc..
