### ISSUE TITLE
Telegram Bot Problem

### ISSUE THREAD

**Issue by RealNavid** [NidukaAkalanka/x-ui-english#39]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi
Thanks for your really nice fork
My telegram bot sends me notifications like panel login and scheduled server status details but when i use commands like /start or etc, i got no answer, should i set webhook or something like that?
Note: SSL is active.

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @RealNavid !
As stated on the readme, all the bot functions only available for v0.2 only. Working on bringing it onto the latest version though. You may expect it very soon.
