### ISSUE TITLE
upload speed is slow

### ISSUE THREAD

**Issue by mjabbarian5** [NidukaAkalanka/x-ui-english#40]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

upload speed is very slow. can you solve it?

### Version of x-ui

<details>

```console
$ x-ui version
# 0.2.1.1
0.2.1.1
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
 ```

</details>

**Comment by NidukaAkalanka** [comment]
Net speeds does not depend on x ui but your server / client ISP and signal strengths
