### ISSUE TITLE
How to transfer x-ui from one server to another

### ISSUE THREAD

**Issue by aliasgari-ka** [NidukaAkalanka/x-ui-english#42]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

How to transfer x-ui from one server to another

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @aliasgari-ka !
Do you want to transfer inbounds and panel settings from one server to another? In that case, upload the .db file at /etc/x-ui-english/x-ui-english.db to a cloud drive where you can get direct link. Even github would fit in. Then, install the x ui normally into your new server. After that, run these commands
`sudo su
cd /etc/x-ui-english/
rm x-ui-english.db -rf
wget <the direct link to the previously uploaded .db file>
chown root x-ui-english.db
systemctl restart x-ui`
Then, run `ls` command. If it returns x-ui-english.db, then you are done. Please use `IP:the port you used for the previous server's x-ui` to access the panel and username : password would be also the ones that you used for the previous server's x-ui.
Please don't forget to place new certificate.crt and private.key files accordingly
