### ISSUE TITLE
Set up ip limit

### ISSUE THREAD

**Issue by Ariojavand** [NidukaAkalanka/x-ui-english#44]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello
I upgraded my panel along with its users to this version, now I'm confused

- In order to limit the current users , do I have to enter the amount of user traffic and the expiration date again??

- In multi-user mode, the amount of traffic and the expiration date in the main menu should be empty?
And set for each user separately?
For example, if the traffic is 50 in the main menu and 20 in the user header, which one is applied?

- Can you give an explanation about the acceptproxyProtocol option?

![image](https://user-images.githubusercontent.com/24471465/205496078-f6da5116-74e6-49ac-bddb-e481a3729186.png)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @Ariojavand !
First off, sorry for your confusion.
- Yeap. You have to enter traffic limit and expiration date, if it isn't showed up correctly at the inbounds list.
- It is recommend to keep the base config's, which you are referring as main menu, empty. And set traffic limits for each client separatly. As per your example, 20 is applied. However, the base config's traffic allowance shouldn't be lesser than the sum of all the client's allowance.
- If you enable proxy protocol, the users may connect to the v2ray server via any proxy forwarding method. Like http proxy.
Please feel free to clear up your all the confusions though!
