### ISSUE TITLE
XRay status: Not running

### ISSUE THREAD

**Issue by amirng** [NidukaAkalanka/x-ui-english#45]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello
Help us, we are getting an error
script say XRay status: Not running
and log:
x-ui[432168]: 2022/12/04 23:12:20 WARNING - client ip job err: truncate ./access.log: no such file or directory
systemd[1]: Stopping x-ui Service...
systemd[1]: x-ui.service: Deactivated successfully.
systemd[1]: Stopped x-ui Service.
systemd[1]: Started x-ui Service.
systemd[1]: Stopping x-ui Service...
systemd[1]: x-ui.service: Deactivated successfully.

### Version of x-ui

<details>

```console
$ x-ui version
# x-ui-english 0.2.2
```

</details>

### x-ui log or xray log

systemd[1]: Stopping x-ui Service...
systemd[1]: x-ui.service: Deactivated successfully.
systemd[1]: Stopped x-ui Service.
systemd[1]: Started x-ui Service.
systemd[1]: Stopping x-ui Service...
systemd[1]: x-ui.service: Deactivated successfully.

**Comment by NidukaAkalanka** [comment]
Hi there @amirng !
Seems like you have upgraded your x ui from an older version. Please refer the guide at https://github.com/NidukaAkalanka/x-ui-english/discussions/27 . 
It'll help you out.
