### ISSUE TITLE
Web API

### ISSUE THREAD

**Issue by AlirezaIvaz** [NidukaAkalanka/x-ui-english#49]
Hi.
Is there any way to manage configurations through web api or is it possible to create own api?

**Comment by HamedAp** [comment]
hi . 
because you use ip in URL ! 
login with domain  like :  panel.xui.com:port !

**Comment by NidukaAkalanka** [comment]
Hi there @AlirezaIvaz !

If you are asking about the api in /web/controller/api.go, it is currently under development. If not, the above comment will help you

**Comment by alirezax5** [comment]
> Hi. Is there any way to manage configurations through web api or is it possible to create own api?

I wrote this repository, maybe it will help you

https://github.com/alirezax5/xuiapi
