### ISSUE TITLE
Please update xray-core

### ISSUE THREAD

**Issue by sajjad-ser** [NidukaAkalanka/x-ui-english#53]
hello please update xray-core to latest version

**Comment by NidukaAkalanka** [comment]
Hi there @sajjad-ser !

The xray core version used here is a modified one. It doesn't belong to the [official xray core dev's](https://github.com/XTLS/Xray-core) versioning.

Furthermore, features like multi user on same port, ip limitation are coming from that modified xray core. There will be no future versions unless I myself publish one with some more feature implementations. 

As long as you need the above mentioned, and highly demanded, features, you have to keep using the current xray core version. It works fine with almost all the v2ray clients
