### ISSUE TITLE
problem after adding key and crt

### ISSUE THREAD

**Issue by M03ED** [NidukaAkalanka/x-ui-english#55]
### Welcome

- [x] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hello.
today i installed x-ui on 2 diffrent vps and on both of them this happen 
![image](https://user-images.githubusercontent.com/50927468/207311855-95239566-ad73-40b6-95d9-2dcb854b3c45.png)
this happen after i add crt and key path to panel 

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by RealNavid** [comment]
Try with both https and http, and if you set your domain on your IP, use your domain instead of your VPS IP to access panel with different browsers.
