### ISSUE TITLE
XRay status: Not running

### ISSUE THREAD

**Issue by Stevemoretz** [NidukaAkalanka/x-ui-english#64]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

How can I see what's wrong, I couldn't find a unit in systemctl about xray and v2ray:

```
sudo systemctl list-units | grep ray
//gives nothing
```

### Version of x-ui

<details>

In the panel and when I run x-ui I get this:
XRay status: Not running

I didn't used to be getting this before I think a system update has caused this

```console
$ x-ui version
X-UI English v Installation is Completed, The Panel has been Started

 --------------------------------------------------------------------- 
   __   __           _    _ _____    ______             _ _     _      
   \ \ / /          | |  | |_   _|  |  ____|           | (_)   | |     
    \ V /   ______  | |  | | | |    | |__   _ __   __ _| |_ ___| |__   
     > <   |______| | |  | | | |    |  __| |  _ \ / _  | | / __|  _ \  
    / . \           | |__| |_| |_   | |____| | | | (_| | | \__ \ | | | 
   /_/ \_\           \____/|_____|  |______|_| |_|\__, |_|_|___/_| |_| 
                                                  __/ |                
                                                 |___/                 
 --------------------------------------------------------------------- 

------------------------------------------------------------------------------
X-UI MANAGEMENT SCRIPT USAGE: 
------------------------------------------------------------------------------
x-ui              - Show the management menu
x-ui start        - Start X-UI panel
x-ui stop         - Stop X-UI panel
x-ui restart      - Restart X-UI panel
x-ui status       - View X-UI status
x-ui enable       - Set X-UI boot self-starting
x-ui disable      - Cancel X-UI boot self-starting
x-ui log          - View x-ui log
x-ui v2-ui        - Migrate V2-UI to X-UI
x-ui update       - Update X-UI panel
x-ui install      - Install X-UI panel
x-ui uninstall    - Uninstall X-UI panel
------------------------------------------------------------------------------

I gives me this not version
```

</details>

### x-ui log or xray log

Would love to know where xray log is 

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @Stevemoretz !

After installation, use your server ip:port that you set to access x ui from a web browser. If there's something wrong with it, please make sure that port is opened properly. 

About systemctl and x ui log, you cam run `systemctl status x-ui`
