### ISSUE TITLE
create user with tg

### ISSUE THREAD

**Issue by aliasgari-ka** [NidukaAkalanka/x-ui-english#66]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

how can i create user with telegram bot

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @aliasgari-ka !

There are so many options to choose from when you are creating a new user. So, it might not be much practical to add a feature like this. You may have a long conversation with the bot. If you did a typo there, it won't be able to correct it by revising. 

Just use the web ui. It is much easier. 

However, I'm working on adding a feature like you can get each client's qr config through the bot. So, still stay excited untill the next release!
