### ISSUE TITLE
A bug in ACME part: wrong description in section 4 and 5

### ISSUE THREAD

**Issue by emranovin** [NidukaAkalanka/x-ui-english#67]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

the script shows this options in section 16: One-click application certificate (ACME script application):
4. Certificate issuing via Cloudflare API for **root-domain**
 5. Certificate issuing via Cloudflare API for **sub-domain** 
 
 but when I want to use my root-domain and enter 4 it wants me **sub-domain** as follow:
 Please enter the domain name to issue certificate (**sub.example.com**):
 
and vise versa:
Please enter the main domain name that requires the application certificate (input format: **example.com**): 

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @emranovin !

Thanks a lot for informing about this bug.

It has now been successfully resolved. Please reinstall acme.sh in order to get rid of this and any future installation won't have this bug.
