### ISSUE TITLE
upload Problem

### ISSUE THREAD

**Issue by cristimo7** [NidukaAkalanka/x-ui-english#73]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hello
fisrt thank for your amazing work.
i used you project and it was fine but now my upload server after connecting is good but after afew seccond it drops to zero and i don't know how to fix i.

### Version of x-ui

1.6.5

### x-ui log or xray log

<details>

```console
# paste log here

0
</details>

**Comment by NidukaAkalanka** [comment]
Hi there @cristimo7 !

Try switching to v2ray core in your client app if it is currently at xray. 

I myself experienced this issue. It is weird and I don't know if it is for everyone who uses this. Willing to investigate

**Comment by shuvvan** [comment]
hi
how do this?!! please telus

> Try switching to v2ray core in your client app if it is currently at xray.

**Comment by cristimo7** [comment]
Hello
itried that and it got better but unfortunately there is not a solution like this for Phone's Client.

**Comment by NidukaAkalanka** [comment]
> hi how do this?!! please telus
> 
> > Try switching to v2ray core in your client app if it is currently at xray.

@shuvvan , well.. It's relative for each client apps. Like.. I use http injector on android and v2rayn on windows and the way of doing it is not the same. Try finding out a option called core or core type in the v2ray configuration. I can't really help with this because it isn't something with x ui but in the client side

**Comment by NidukaAkalanka** [comment]
> Hello itried that and it got better but unfortunately there is not a solution like this for Phone's Clients.

@cristimo7 Glad to hear you got better. Actually I myself experienced this issue on a phone client, after changing the core type. Http injector on Android to be specific. Its developers just recently added that cores selection so I think it's an issue on their side. 

Using v2rayN on windows. Never experienced this issue. Core type is v2ray by default.
