### ISSUE TITLE
use mainsteream xray-core

### ISSUE THREAD

**Issue by jahaniam** [NidukaAkalanka/x-ui-english#74]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Would be nice to drop support for "customized xray-core" and use the mainstream xray-core. Xray-core has a lot of new features that you don't need to worry importing it into the customized version. More contributed could help adapt the x-UI to the new xray-core as well even if it means dropping support for limiting IP.

Some new features include xtls-vision

### Version of x-ui

Would be nice to drop support for "customized xray-core" and use the mainstream xray-core. Xray-core has a lot of new features that you don't need to worry importing it into the customized version. More contributed could help adapt the x-UI to the new xray-core as well even if it means dropping support for limiting IP.

Some new features include xtls-vision

### x-ui log or xray log

Would be nice to drop support for "customized xray-core" and use the mainstream xray-core. Xray-core has a lot of new features that you don't need to worry importing it into the customized version. More contributed could help adapt the x-UI to the new xray-core as well even if it means dropping support for limiting IP.

Some new features include xtls-vision

**Comment by NidukaAkalanka** [comment]
Hi there @jahaniam !

As long as you need the features like multi user on same port with individual arguments and IP limitation, you should keep using the customized xray core. 

It has nothing to do with [XTLS's ](https://www.github.com/XTLS/Xray-core) versioning. But will try to merge the official core's new functions as soon as possible.
