### ISSUE TITLE
Switch version doesn't work!

### ISSUE THREAD

**Issue by roudika** [NidukaAkalanka/x-ui-english#76]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

I am using 1.6.4 version, when I click on Switch version it says there is 1.6.5, when I click on it to switch, it said version switched succesfuly but it doesn't change the front panel version from 1.6.4. 
I have tried to restart the panel or update via the script. the issue still exist.
any suggestion how to fix the issue?

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by TimurBigs** [comment]
Hi

Why the panel doesn't have 1.7.0 version to update.
Please fix it.

Thanks

**Comment by NidukaAkalanka** [comment]
Hi there @pulsarice , @TimurBigs and @roudika !

The features like multi user on same port and IP limitation, which were highly demanded, are comes from the xray core version currently being used. There's no need to switch it. 

It has nothing to do with official xray core's versioning. But will try to merge its new features ASAP.

Yeah. Even I have found this bug and gave a few efforts to fix it up; which didn't work. I may keep trying.. But.. There's no need of switching it.
