### ISSUE TITLE
Xray

### ISSUE THREAD

**Issue by Angize** [NidukaAkalanka/x-ui-english#78]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi, Please update the xray version

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by amihos** [comment]
1.7 is out now.

**Comment by Angize** [comment]
But in the panel higher than 1.6.5, it is not possible to upgrade

**Comment by NidukaAkalanka** [comment]
Hi there @Angize !

The panel has a customized core and it has nothing to do with official xray core developer's versioning. Tge highly demanded features like multi users with more arguments on same port and IP limitation are coming from that costomized xray core. 

@amihos is talking about the official xray core developers release. It isn't what is being used here. Please refer https://github.com/NidukaAkalanka/x-ui-english/issues/76 and https://github.com/NidukaAkalanka/x-ui-english/issues/74

But I'll try to merge the official core's good features without collapsing with the features implemented by myself.
