### ISSUE TITLE
Xray Core Upgrading 

### ISSUE THREAD

**Issue by NidukaAkalanka** [NidukaAkalanka/x-ui-english#81]
Hi everyone!

If you are about to open up an issue saying "Please upgrade the xray core version.. A higher version is released.." Please, just read this!

The current core version is not the one the official one. Xray cores are officially released by [XTLS](https://github.com/XTLS/Xray-core/) But the one being used here is a customized one. It has nothing to do with their semantic versioning. It was customized for implementing features such as multi users with more arguments on the same port and IP limitation. Official cores never had those highly demanded features (so far) 

If you want to see a higher version at xray core version or if you want to switch to a lower version for some reasons, like regarding IOS, then you have to say good bye to the above said features; which you would not.

If the official xray core developers release any newer version with many useful features, I'll try to implement those without collapsing with the custom added features.

I know there's a bug when trying to switching the xray core version at the web panel. After giving a few efforts which were unsuccessful, I gave up on trying to fix it up because it is like.. Not meant to be switched.

If you are interested on reading more about this customized core story, please refer to https://github.com/NidukaAkalanka/x-ui-english/discussions/60

Just pinning this on the issues tab because I'm tired of replying the same thing again and again to so many issues opened requesting xray core upgrade. 

If you are having any other issues, please open up an issue. You are warmly welcomed and would love to help you out to fix up the issue. 

Thanks and Regards,
Niduka A 
🤍

**Comment by Angize** [comment]
Does that mean we will never go higher than this version?

**Comment by NidukaAkalanka** [comment]
> Does that mean we will never go higher than this version?

@Angize , we will go higher than this version once the official xray core developers released a few more versions with new useful functions. So I can take that version's source code and publish a higher version with the custom features. Merging those features and official core release should be done so carefully and it takes time. When the officials release more versions, the latest one will contain all of those features. I'll take it's source code and merge it with the above said features. 

Does the current version lacks stability or do you need more features that are unavailable currently but available in official releases? 

Nonetheless, if you desperately need to use newer xray core versions, you can simply swich to [X-UI English.old](https://github.com/NidukaAkalanka/x-ui-english.old/) or [X-UI English v0.2](https://github.com/NidukaAkalanka/x-ui-english/releases/tag/0.2) but you have to forget the custom added features; which aren't recommended

**Comment by NidukaAkalanka** [comment]
UPDATE :
Even after pinning this up, people still opening up issues regarding xray core and its version. So, I decided to remove the feature of switching the core versions. Now onwards, you'll see nothing but the current version on the switching pane. 

But don't worry.. As I said before, we'll go higher than the current version after some time. In that case, you may get it upgraded with the single command installing/upgrading or with the x-ui menu

**Comment by ZASS-DEV** [comment]
hello.
first of all thank you for the great job. i see what you say about xray upgrading. but the question i want to ask : is there a way we do it manually ? i mean using your xui options and only manually upgrade xray by my self ? so i dont wanna replace your xui only wanna upgrade xray core manually . is it possible ? or  there is not a way .
