### ISSUE TITLE
XRAY version does not update to 1.65

### ISSUE THREAD

**Issue by amihos** [NidukaAkalanka/x-ui-english#86]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

A fresh install. Right of the bat the xray version is set at 1.64. When you click to upgrade it to 1.65 it accepts and shows success but the version wont change.

### Version of x-ui

latest version
0.2.1.2

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @amihos !

Please read the pinned issue and all its comments, which can be found [here](https://github.com/NidukaAkalanka/x-ui-english/issues/81)
