### ISSUE TITLE
upload problem

### ISSUE THREAD

**Issue by iman32** [NidukaAkalanka/x-ui-english#87]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi 
my downloads vs. upload is unusual.
like I started my panel just few ours and didn't really use it but I have uploaded 4 GB and 10 time more than download.
It's uploading itself and lowering my speed.

### Version of x-ui

x-ui-english 0.2.1.2

### x-ui log or xray log

Logs begin at Sun 2020-03-15 05:34:08 UTC. --
Dec 29 16:32:58 bimh systemd[1]: Started x-ui Service.
Dec 29 16:32:58 bimh systemd[1]: Stopping x-ui Service...
Dec 29 16:32:58 bimh systemd[1]: Stopped x-ui Service.
Dec 29 16:32:58 bimh systemd[1]: Started x-ui Service.
Dec 29 16:32:58 bimh x-ui[1685]: 2022/12/29 16:32:58 x-ui-english 0.2.1.2
Dec 29 16:32:58 bimh x-ui[1685]: 2022/12/29 16:32:58 INFO - web server run http on 0.0.0.0:38378
Dec 29 16:34:05 bimh x-ui[1685]: 2022/12/29 16:34:05 [sessions] ERROR! securecookie: the value is not valid
Dec 29 16:34:21 bimh x-ui[1685]: 2022/12/29 16:34:21 INFO - sysnum login success,Ip Address:5.217.45.82
Dec 29 16:34:21 bimh x-ui[1685]: 2022/12/29 16:34:21 WARNING - sendMsgToTgbot failed,GetTgBotToken fail: <nil>
Dec 29 16:34:21 bimh x-ui[1685]: 2022/12/29 16:34:21 [sessions] ERROR! securecookie: the value is not valid
Dec 29 16:34:21 bimh x-ui[1685]: 2022/12/29 16:34:21 INFO - user 1 login success
Dec 29 18:43:43 bimh systemd[1]: Stopping x-ui Service...
Dec 29 18:43:43 bimh systemd[1]: Stopped x-ui Service.
-- Reboot --
Dec 29 18:44:08 bimh systemd[1]: Started x-ui Service.
Dec 29 18:44:09 bimh x-ui[849]: 2022/12/29 18:44:09 x-ui-english 0.2.1.2
Dec 29 18:44:09 bimh x-ui[849]: 2022/12/29 18:44:09 INFO - web server run http on 0.0.0.0:38378
Dec 29 18:57:40 bimh systemd[1]: Stopping x-ui Service...
Dec 29 18:57:40 bimh systemd[1]: Stopped x-ui Service.
Dec 29 18:57:50 bimh systemd[1]: Started x-ui Service.
Dec 29 18:57:50 bimh systemd[1]: Stopping x-ui Service...
Dec 29 18:57:50 bimh systemd[1]: Stopped x-ui Service.
Dec 29 18:57:50 bimh systemd[1]: Started x-ui Service.
Dec 29 18:57:50 bimh x-ui[5173]: 2022/12/29 18:57:50 x-ui-english 0.2.1.2
Dec 29 18:57:50 bimh x-ui[5173]: 2022/12/29 18:57:50 INFO - web server run http on 0.0.0.0:38378
Dec 29 22:29:51 bimh x-ui[5173]: 2022/12/29 22:29:51 [sessions] ERROR! securecookie: the value is not valid
Dec 29 22:30:00 bimh x-ui[5173]: 2022/12/29 22:30:00 INFO - sysnum login success,Ip Address:5.208.64.151
Dec 29 22:30:00 bimh x-ui[5173]: 2022/12/29 22:30:00 WARNING - sendMsgToTgbot failed,GetTgBotToken fail: <nil>
Dec 29 22:30:00 bimh x-ui[5173]: 2022/12/29 22:30:00 [sessions] ERROR! securecookie: the value is not valid
Dec 29 22:30:00 bimh x-ui[5173]: 2022/12/29 22:30:00 INFO - user 1 login success

**Comment by NidukaAkalanka** [comment]
Hi there @iman32! 

Please check if your panel URL and login details are comprised. Maybe someone else has logged into the x ui web panel and using it.

Also, check whether no one else is ssh logged into your server. There are many botnets out there trying to brute-force servers. Even one of my servers got such an attack and I noticed that from its abnormally aggressive outbound traffic usage. 

Are there any vpn kind of services running on your server? Or any other process that utilizes network traffic? Like a web server? Also in that case, you may see that particular process's network consumption being calculated by x ui. 

I think this is an issue with your server rather than the x ui

**Comment by iman32** [comment]
Yes i think It is with my country sanctions
Stupid country
