### ISSUE TITLE
the pannel is not running

### ISSUE THREAD

**Issue by cristimo7** [NidukaAkalanka/x-ui-english#88]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hello 
i installed your program and it worked fine.
but today i install a new one and it not running and show an error.
one on my old server is now seems to not working correctly and show the same error.
the error is this.
open bin/config.json: no such file or directory

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @cristimo7 !

Please consider uninstalling and installing the x ui once again to see if this is getting fixed as I've neither experienced nor met someone else who had an issue as described.

If you can provide x-ui logo, it'll be easier for me to understand what's wrong in your end
