### ISSUE TITLE
Download stats zero byte

### ISSUE THREAD

**Issue by hamedap** [NidukaAkalanka/x-ui-english#9]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

![Screenshot_20221112-195517_Chrome](https://user-images.githubusercontent.com/109583222/201484091-122344ca-2fc3-480b-9018-a237012629a8.jpg)

Users download stats are 0 all time .
Just upload works .

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```
Latest
</details>

### x-ui log or xray log

<details>

```console
# paste log here
```
  

</details>

**Comment by hamedap** [comment]
It does not work after update panel to 0.2

**Comment by shahrooz1349** [comment]
I have the same problem

> It does not work after update panel to 0.2

**Comment by moslem2013** [comment]
Yes, it is a problem for me
The second problem is that after installing the script, accounts created with the original version are deleted 😐😐😐😐
Please solve this problem and Add backup account

**Comment by NidukaAkalanka** [comment]
Hi @moslem2013 @shahrooz1349 and @hamedap !
Thanks a lot for informing this issue and please accept my sincere apologizes for any inconveniences experienced. 
Can someone confirm that, the download stats being not calculated occurs only **after updating**?

**Comment by NidukaAkalanka** [comment]
Hi @moslem2013 , in the new version, there's a prompt asking whether you want to delete the previous version completely and install the new one. You should provide Y or N to that and the default operation is **N**. If you chose Y there, it would be a re-install. Do you remember what was your option there? 
If you chose Y, the problem with inbounds isn't an issue. 
But.. Yeah. The download data being not calculated seems to be a bug, unfortunately.

**Comment by moslem2013** [comment]
hi @NidukaAkalanka
After type N, the installation is canceled and it is not install script
To install need Type Y And After install completely Removed accounts created with the original version 🥺🙁☹️

**Comment by shahrooz1349** [comment]
> Hi@moslem2013 @shahrooz1349and@hamedap ! Thanks a lot for informing this issue and please accept my sincere apologizes for any inconveniences experienced. Can someone confirm that, the download stats being not calculated occurs only **after updating**?

Dear Developer
I directly installed the latest version but I got this problem

regard

**Comment by NidukaAkalanka** [comment]
@moslem2013 @shahrooz1349 , Thanks a lot for your replies. 
Identified the bug. Will be taking necessary steps to fix it up as soon as possible and will release version 0.2.1, which will bring the solutions for theses issues. 
Once again, please accept my sincere apologizes for any inconveniences experienced. And thanks a lot for informing.
Regards 
🤍

**Comment by shahrooz1349** [comment]
> @moslem2013 @shahrooz1349 , Thanks a lot for your replies. Identified the bug. Will be taking necessary steps to fix it up as soon as possible and will release version 0.2.1, which will bring the solutions for theses issues. Once again, please accept my sincere apologizes for any inconveniences experienced. And thanks a lot for informing. Regards 🤍

Thank you for your efforts, dear developer

**Comment by moslem2013** [comment]
hi @NidukaAkalanka find new bug in the x-ui Commands
panel ipv4 loggin address = Servrer IP:0.0.0.0:Port
0.0.0.0 no need 💯 
![54353453535](https://user-images.githubusercontent.com/53048658/201824226-306e123b-c063-42ba-899c-08ad4ec75494.png)

**Comment by NidukaAkalanka** [comment]
> hi @NidukaAkalanka find new bug in the x-ui Commands panel ipv4 loggin address = Servrer IP:0.0.0.0:Port 0.0.0.0 no need 💯 ![54353453535](https://user-images.githubusercontent.com/53048658/201824226-306e123b-c063-42ba-899c-08ad4ec75494.png)

@moslem2013 Is it an IPV6 only server?

**Comment by moslem2013** [comment]
Yes

**Comment by moslem2013** [comment]
@NidukaAkalanka  My internet company in Iran Detected my Panel and blocked  My panel Now it opens with VPN 
How to bypass and open panel Without VPN ? 😭😭😭😭😭

**Comment by NidukaAkalanka** [comment]
> Yes

@moslem2013 , well... Honestly, though I've experienced IPV6 only, I haven't done anything on a server with only IPV4. And this seems to be not a global issue like the download data being not calculated. Weird  😶

![tempsnip](https://user-images.githubusercontent.com/97357554/201835793-5df16e0f-cf7b-4783-8a70-b9e0f1b86226.png)

**Comment by jahaniam** [comment]
Thanks for providing this repo. This is amazing. I'm looking forward to the fix. Really appreciated.

**Comment by hamedap** [comment]
Any news about fix Bug ?

**Comment by moslem2013** [comment]
please faster bug fix

**Comment by moslem2013** [comment]
in new version problem not fixed and after install new version command error

mv: cannot stat '/etc/x-ui.db.bak': No such file or directory


![442242424](https://user-images.githubusercontent.com/53048658/202914397-6197a2ed-c65e-49d4-b743-940127b85cf9.png)

**Comment by NidukaAkalanka** [comment]
Hey, @jahaniam @moslem2013 @shahrooz1349 @hamedap !
Please check the [Release 0.2.1](https://github.com/NidukaAkalanka/x-ui-english/releases/tag/0.2.1). It has this particular issue was resolved.
Thanks a lot for your contribution via opening up this issue, also!
Regards,
🤍
