### ISSUE TITLE
bot telegram

### ISSUE THREAD

**Issue by mohammadRezaeian** [NidukaAkalanka/x-ui-english#97]
hi thank you for create this project
i trying use bot telegram
but when i set configuration telegram bot in web panel Project 
it's just send me list profiles and start or another command in Readme can't work.

**Comment by NidukaAkalanka** [comment]
Hi there @mohammadRezaeian !

Only a part of telegram bot is currently available for the latest release. It is clearly mentioned on the readme. Bot is fully available on v0.2, which is an older version that lacks features like ip limitation, multi users on same port and etc.. Just wait till the next release so it will include a fully working bot.

**Comment by graymind123** [comment]
https://github.com/NidukaAkalanka/x-ui-english/pull/105/commits/e4a54214f9e66c1beebd87294b8ca916b38f9a52

**Comment by graymind123** [comment]
> hi thank you for create this project i trying use bot telegram but when i set configuration telegram bot in web panel Project it's just send me list profiles and start or another command in Readme can't work.

if you are in hurry, you can see this https://github.com/NidukaAkalanka/x-ui-english/pull/105/commits/e4a54214f9e66c1beebd87294b8ca916b38f9a52
