### ISSUE TITLE
geo ip

### ISSUE THREAD

**Issue by shahabghavidel** [NidukaAkalanka/x-ui-english#99]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello, there is no explanation for using geo ip
 For example, when we use VPN
 When we enter the internal sites of the country, our IP servers are detected
 and limit
 I request you to provide an explanation for limiting the IPs of internal sites
 so that users cannot enter Iranian sites using our VPNs

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @shahabghavidel !

Well, you can have a nice explanation about geoip amd its usage in v2ray configuration here : https://github.com/v2fly/geoip
